FROM node:22-alpine

RUN apk update && apk add \
    python3 \
    make \
    g++ \
    gcc \
    libc-dev \
    linux-headers \
    libusb-dev \
    eudev-dev \
    pkgconf \
    ca-certificates && update-ca-certificates

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

EXPOSE 5174

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]